-- 
-- insert into productos (name, price) values ('Strawberries', 959.06);
-- insert into productos (name, price) values ('Towels - Paper / Kraft', 634.25);
-- insert into productos (name, price) values ('Veal - Inside', 486.73);
-- insert into productos (name, price) values ('Lychee', 743.09);
-- insert into productos (name, price) values ('Turnip - Mini', 636.62);
-- insert into productos (name, price) values ('Tart Shells - Savory, 3', 188.28);
-- insert into productos (name, price) values ('Pepper - Chillies, Crushed', 336.1);
-- insert into productos (name, price) values ('Cheese - Parmesan Cubes', 379.38);
-- insert into productos (name, price) values ('Danishes - Mini Raspberry', 493.13);
-- insert into productos (name, price) values ('Pastry - Butterscotch Baked', 881.69);
-- insert into productos (name, price) values ('Cleaner - Pine Sol', 581.09);
-- insert into productos (name, price) values ('Juice - Cranberry, 341 Ml', 613.32);
-- insert into productos (name, price) values ('Jolt Cola', 183.46);
-- insert into productos (name, price) values ('Plaintain', 618.69);
-- insert into productos (name, price) values ('Sauerkraut', 584.14);
-- insert into productos (name, price) values ('Pastry - Mini French Pastries', 794.0);
-- insert into productos (name, price) values ('Towels - Paper / Kraft', 429.66);
-- insert into productos (name, price) values ('Cheese - Montery Jack', 706.21);
-- insert into productos (name, price) values ('Cilantro / Coriander - Fresh', 421.44);
-- insert into productos (name, price) values ('Glove - Cutting', 204.76);
-- insert into productos (name, price) values ('Vegetable - Base', 218.87);
-- insert into productos (name, price) values ('General Purpose Trigger', 563.5);
-- insert into productos (name, price) values ('Soup Campbells Mexicali Tortilla', 260.8);
-- insert into productos (name, price) values ('Bread - Raisin', 471.98);
-- insert into productos (name, price) values ('Beef - Sushi Flat Iron Steak', 663.52);
-- insert into productos (name, price) values ('Puff Pastry - Sheets', 388.64);
-- insert into productos (name, price) values ('Soup - Base Broth Chix', 297.25);
-- insert into productos (name, price) values ('Wine - White, Antinore Orvieto', 348.41);
-- insert into productos (name, price) values ('Fish - Atlantic Salmon, Cold', 934.02);
-- insert into productos (name, price) values ('Cakes Assorted', 216.47);
-- insert into productos (name, price) values ('Stock - Beef, Brown', 835.4);
-- insert into productos (name, price) values ('Turkey - Breast, Double', 678.87);
-- insert into productos (name, price) values ('Chips Potato All Dressed - 43g', 495.08);
-- insert into productos (name, price) values ('Beans - Butter Lrg Lima', 689.14);
-- insert into productos (name, price) values ('Broom And Brush Rack Black', 835.19);
-- insert into productos (name, price) values ('Compound - Mocha', 799.54);
-- insert into productos (name, price) values ('Yogurt - Banana, 175 Gr', 232.8);
-- insert into productos (name, price) values ('Bread - Dark Rye, Loaf', 598.25);
-- insert into productos (name, price) values ('Pike - Frozen Fillet', 753.31);
-- insert into productos (name, price) values ('Tea - Black Currant', 986.77);
-- insert into productos (name, price) values ('Flour - Semolina', 347.12);
-- insert into productos (name, price) values ('Lettuce - Radicchio', 84.95);
-- insert into productos (name, price) values ('Container - Hngd Cll Blk 7x7x3', 956.02);
-- insert into productos (name, price) values ('Ginger - Pickled', 910.11);
-- insert into productos (name, price) values ('Ecolab - Ster Bac', 773.49);
-- insert into productos (name, price) values ('Soup - Campbells, Minestrone', 171.55);
-- insert into productos (name, price) values ('Bread - French Stick', 43.93);
-- insert into productos (name, price) values ('Beef - Bones, Cut - Up', 532.99);
-- insert into productos (name, price) values ('Kiwano', 837.19);
-- insert into productos (name, price) values ('Soup - Campbells Mac N Cheese', 894.74);
-- insert into productos (name, price) values ('Wine - Piper Heidsieck Brut', 63.98);
-- insert into productos (name, price) values ('Ham - Cooked Bayonne Tinned', 532.48);
-- insert into productos (name, price) values ('Pepper - Cayenne', 625.09);
-- insert into productos (name, price) values ('Squash - Acorn', 746.41);
-- insert into productos (name, price) values ('Squid - U 5', 811.9);
-- insert into productos (name, price) values ('Eel - Smoked', 898.0);
-- insert into productos (name, price) values ('Wine - Chardonnay South', 621.76);
-- insert into productos (name, price) values ('Onion Powder', 7.92);
-- insert into productos (name, price) values ('Tumeric', 638.13);
-- insert into productos (name, price) values ('Wine La Vielle Ferme Cote Du', 231.18);
-- insert into productos (name, price) values ('Towel - Roll White', 472.22);
-- insert into productos (name, price) values ('Rice - 7 Grain Blend', 69.01);
-- insert into productos (name, price) values ('Chips Potato Swt Chilli Sour', 28.83);
-- insert into productos (name, price) values ('Juice - Mango', 985.77);
-- insert into productos (name, price) values ('Sauce - Gravy, Au Jus, Mix', 240.24);
-- insert into productos (name, price) values ('Onions - Red', 743.96);
-- insert into productos (name, price) values ('Beef - Tenderlion, Center Cut', 332.47);
-- insert into productos (name, price) values ('Creme De Menthe Green', 165.44);
-- insert into productos (name, price) values ('Cheese - Mozzarella, Buffalo', 5.28);
-- insert into productos (name, price) values ('Bay Leaf Fresh', 304.54);
-- insert into productos (name, price) values ('Pizza Pizza Dough', 481.9);
-- insert into productos (name, price) values ('Chinese Foods - Plain Fried Rice', 525.67);
-- insert into productos (name, price) values ('Pastry - Banana Muffin - Mini', 885.54);
-- insert into productos (name, price) values ('Gherkin - Sour', 50.94);
-- insert into productos (name, price) values ('The Pop Shoppe - Cream Soda', 724.7);
-- insert into productos (name, price) values ('Oranges', 990.85);
-- insert into productos (name, price) values ('Otomegusa Dashi Konbu', 402.68);
-- insert into productos (name, price) values ('Cheese - Gouda', 672.1);
-- insert into productos (name, price) values ('Eggplant Oriental', 581.49);
-- insert into productos (name, price) values ('Sauce - Alfredo', 458.55);
-- insert into productos (name, price) values ('Soup Campbells Turkey Veg.', 434.27);
-- insert into productos (name, price) values ('Triple Sec - Mcguinness', 948.25);
-- insert into productos (name, price) values ('Yogurt - Assorted Pack', 981.0);
-- insert into productos (name, price) values ('Taro Root', 670.51);
-- insert into productos (name, price) values ('Otomegusa Dashi Konbu', 890.92);
-- insert into productos (name, price) values ('Pepsi - 600ml', 924.79);
-- insert into productos (name, price) values ('Lamb - Loin, Trimmed, Boneless', 393.32);
-- insert into productos (name, price) values ('Beans - Kidney White', 538.54);
-- insert into productos (name, price) values ('Versatainer Nc - 9388', 449.54);
-- insert into productos (name, price) values ('Country Roll', 428.65);
-- insert into productos (name, price) values ('Doilies - 5, Paper', 736.21);
-- insert into productos (name, price) values ('Muffins - Assorted', 807.93);
-- insert into productos (name, price) values ('Syrup - Monin - Passion Fruit', 764.73);
-- insert into productos (name, price) values ('Pasta - Gnocchi, Potato', 521.64);
-- insert into productos (name, price) values ('Chocolate Bar - Coffee Crisp', 512.92);
-- insert into productos (name, price) values ('Soup Campbells - Tomato Bisque', 496.91);
-- insert into productos (name, price) values ('Almonds Ground Blanched', 413.57);
-- insert into productos (name, price) values ('Glucose', 846.96);
-- insert into productos (name, price) values ('Wine - Magnotta, White', 747.4);
-- insert into productos (name, price) values ('Bread - Pita', 717.27);



-- Inserts para la tabla category
INSERT INTO category (name, description) VALUES ('Lácteos', 'Productos derivados de la leche');
INSERT INTO category (name, description) VALUES ('Carnes', 'Diferentes tipos de carnes y embutidos');
INSERT INTO category (name, description) VALUES ('Bebidas', 'Bebidas alcohólicas y no alcohólicas');
INSERT INTO category (name, description) VALUES ('Verduras', 'Verduras frescas y orgánicas');
INSERT INTO category (name, description) VALUES ('Panadería', 'Productos de panadería y repostería');
INSERT INTO category (name, description) VALUES ('Frutas', 'Variedad de frutas nacionales e importadas');
INSERT INTO category (name, description) VALUES ('Enlatados', 'Comida enlatada de larga duración');
INSERT INTO category (name, description) VALUES ('Congelados', 'Alimentos congelados para su conservación');
INSERT INTO category (name, description) VALUES ('Cereales', 'Productos a base de cereales y granos');
INSERT INTO category (name, description) VALUES ( 'Especias', 'Variedad de condimentos y especias');

-- Inserts para la tabla productos
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Leche Deslactosada', 20.5, 50, 15.0, 1);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Carne de Res', 150.0, 30, 120.0, 2);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Cerveza Artesanal', 65.0, 100, 45.0, 3);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Espinaca', 15.0, 80, 10.0, 4);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Pan Integral', 35.0, 40, 25.0, 5);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Manzanas Roas', 30.0, 60, 20.0, 6);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Atún enlatado', 45.0, 90, 35.0, 7);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Helado de Chocolate', 80.0, 25, 60.0,NULL);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Avena Instantánea', 25.0, 70, 15.0, 10);
INSERT INTO productos (name, price, stock, fabrication_cost, category_id) VALUES ('Pimienta Negra', 10.0, 200, 5.0, 10);